# Use the official Node.js Alpine image as the base
FROM node:16.20.2-alpine

# Set the working directory
WORKDIR /frontend

# Copy package.json and package-lock.json
COPY frontend/ .

# Install dependencies
RUN npm install --production

# Expose the port your React app runs on (e.g., 3000)
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
