# Build the React frontend
FROM node:16.20.2 AS frontend-build

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm install --global npm@8.19.4
RUN npm install

COPY frontend/ .
RUN npm run build

# Serve the React frontend
FROM nginx:stable-alpine

COPY --from=frontend-build /app/frontend/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
