# Generated by Django 5.0.1 on 2024-03-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_profit_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='profit_loss',
            field=models.IntegerField(default=0),
        ),
    ]
