# Generated by Django 5.0.1 on 2024-03-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sales_total_receivable_amt_alter_sales_profit_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='profit_loss',
        ),
    ]
