# Generated by Django 5.0.1 on 2024-03-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_sales_grand_total_alter_sales_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='total_receivable_amt',
        ),
        migrations.AddField(
            model_name='sales',
            name='profit_loss',
            field=models.IntegerField(default=0),
        ),
    ]
