# Generated by Django 5.0.1 on 2024-03-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='profit_loss',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
