# Generated by Django 5.0.1 on 2024-03-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sales_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='profit_loss',
            field=models.IntegerField(default=0),
        ),
    ]
