# Generated by Django 5.0.1 on 2024-03-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sales_profit_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='profit_loss',
        ),
    ]
