# Generated by Django 4.2.7 on 2024-01-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('purchased_date', models.DateField()),
                ('items_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('amt_paid', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('grand_total', models.IntegerField()),
                ('payable_amt', models.IntegerField()),
            ],
        ),
    ]
