# Generated by Django 5.0.1 on 2024-03-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_purchase_purchased_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payable_amt',
            field=models.IntegerField(default=0),
        ),
    ]
